[package]
name = "contracts_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.9.9"
ic-cdk = "0.11"
ic-cdk-macros = "0.8"
serde = { version = "1.0", features = ["derive"] }
calimero-sdk = "0.2.0"
ic-stable-structures = "0.5.6"
