import { type Models } from 'appwrite';

/**
 * This file is auto-generated by the Appwrite CLI. 
 * You can regenerate it by running `appwrite types -l ts /home/nathfavour/Documents/code/buildathonzx/whisperrnote`.
 */

export type Users = Models.Document & {
  id: string | null;
  email: string | null;
  name: string | null;
  passwordHash: string | null;
  walletAddress: string | null;
  createdAt: string | null;
  updatedAt: string | null;
}

export type Notes = Models.Document & {
  id: string | null;
  title: string | null;
  content: string | null;
  createdAt: string | null;
  updatedAt: string | null;
  userId: string | null;
  isPublic: boolean | null;
  tags: string[] | null;
}

export type Tags = Models.Document & {
  id: string | null;
  name: string | null;
  notes: string[] | null;
  createdAt: string | null;
}

export type ApiKeys = Models.Document & {
  id: string | null;
  key: string | null;
  name: string | null;
  userId: string | null;
  createdAt: string | null;
  lastUsed: string | null;
  expiresAt: string | null;
}

export type BlogPosts = Models.Document & {
  id: string | null;
  title: string | null;
  content: string | null;
  createdAt: string | null;
  updatedAt: string | null;
  authorId: string | null;
}

