

















}    }        return message;    function getMessage() public view returns (string memory) {    }        message = newMessage;    function updateMessage(string memory newMessage) public {    }        message = initialMessage;    constructor(string memory initialMessage) {    string public message;contract CalimeroContract {pragma solidity ^0.8.0;// SPDX-License-Identifier: MIT