name: whisperrnote_app
description: "WhisperNote Flutter App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  http: ^1.2.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  flutter_markdown: ^0.6.20
  file_picker: ^6.1.1
  path_provider: ^2.1.5
  flutter_animate: ^4.5.0
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
